# Generated by Django 4.2.19 on 2025-02-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_author_name_author_bio_author_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
