# Generated by Django 4.2.19 on 2025-02-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_pagess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagess',
            new_name='PagesMenu',
        ),
    ]
