# Generated by Django 4.2.19 on 2025-02-28 10:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_rename_pagess_pagesmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesmenu',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='PagesMenu_images'),
        ),
        migrations.AlterField(
            model_name='pagesmenu',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
