# Generated by Django 4.2.19 on 2025-03-01 03:23

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_pagesmenu_image_alter_pagesmenu_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_images/'),
        ),
    ]
