# Generated by Django 4.2.19 on 2025-03-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_category_cid_alter_post_image'),
    ]

    operations = [
    ]
