# Generated by Django 4.2.19 on 2025-03-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_update_unique_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cid',
        ),
    ]
