# Generated by Django 4.2.19 on 2025-03-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
