# Generated by Django 4.2.10 on 2025-03-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_comment_delete_pagesmenu_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
